apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-crbw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-crbw
    app.kubernetes.io/part-of: build-suite-test-application-gmaj
  name: build-suite-test-component-git-source-crbw
  namespace: build-templates-e2e
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-git-source-crbw
status:
  loadBalancer: {}
